jest.mock('@/lib/supabase',()=>({supabase:{from:jest.fn()}}));
jest.mock('@/lib/daily-health-score',()=>({scoreContext:jest.fn(),readScore:jest.fn()}));
import { supabase } from '@/lib/supabase';
import { scoreContext, readScore } from '@/lib/daily-health-score';
import { gymRewardStatus } from '@/lib/gym-reward-status';
const w={id:'w',start_at:'2026-09-13T11:00:00+00:00',end_at:'2026-09-13T11:30:00+00:00',sport_name:'Strength',workout_score:49.4,score_input_valid:true,score_state:'SCORED'};
let values:Record<string,unknown>;
const saved={...process.env};
beforeEach(()=>{jest.useFakeTimers().setSystemTime(new Date('2026-09-13T12:00:00Z'));process.env.GYM_WORKOUT_VERIFICATION_ENABLED='true';process.env.GYM_DAILY_REWARDS_ENABLED='true';
 (scoreContext as jest.Mock).mockResolvedValue({gymId:'gym',today:'2026-09-13',timezone:'UTC',membershipStart:'2026-09-01'});(readScore as jest.Mock).mockResolvedValue({score:43.5,subtotal:43.5,complete:true});
 values={gym_reward_config:{singleton:true,verification_enabled:true,rewards_enabled:true,effective_date:'2026-09-13'},whoop_workouts:[w],gym_workout_verifications:[],daily_reward_entitlements:[]};
 (supabase.from as jest.Mock).mockImplementation(table=>{const chain:any={};for(const m of ['select','eq','single','is','gte','order','limit'])chain[m]=()=>chain;chain.then=(resolve:any)=>Promise.resolve({data:values[table],error:null}).then(resolve);return chain;});
});
afterEach(()=>jest.useRealTimers());afterAll(()=>{process.env=saved;});
test('an imported ended workout offers scanning without claiming points credited',async()=>{const s=await gymRewardStatus('member');expect(s.workouts[0]).toMatchObject({canScan:true,verified:false});expect(s.creditedPoints).toBe(0);expect(s.estimatedPoints).toBe(43.5);});
test('equivalent timestamp representations remain verified; altered timestamps require review',async()=>{
 values.gym_workout_verifications=[{workout_id:'w',gym_id:'gym',start_at:'2026-09-13T11:00:00.000Z',end_at:'2026-09-13T11:30:00.000Z'}];
 expect((await gymRewardStatus('member')).workouts[0]).toMatchObject({canScan:false,verified:true});
 values.whoop_workouts=[{...w,end_at:'2026-09-13T11:40:00Z'}];expect((await gymRewardStatus('member')).workouts[0]).toMatchObject({canScan:false,verified:false,status:expect.stringContaining('needs review')});
});
test('expired scan window and disabled setup never invite an accepted scan',async()=>{jest.setSystemTime(new Date('2026-09-13T15:00:00Z'));expect((await gymRewardStatus('member')).workouts[0].canScan).toBe(false);jest.setSystemTime(new Date('2026-09-13T12:00:00Z'));delete process.env.GYM_WORKOUT_VERIFICATION_ENABLED;expect((await gymRewardStatus('member')).workouts[0].canScan).toBe(false);});
