jest.mock('@/lib/supabase', () => ({supabase:{rpc:jest.fn()}}));
jest.mock('@/lib/whoop/sync', () => ({syncMemberWorkouts:jest.fn(),SyncBusyError:class extends Error{}}));
import {NextRequest} from 'next/server';
import {supabase} from '@/lib/supabase';
import {syncMemberWorkouts,SyncBusyError} from '@/lib/whoop/sync';
import {GET,POST} from '@/app/api/internal/whoop/process/route';
const original=process.env.CRON_SECRET;
const request=(secret='secret')=>new NextRequest('https://thrivv.dev/api/internal/whoop/process',{headers:{authorization:`Bearer ${secret}`}});
beforeEach(()=>{jest.clearAllMocks();process.env.CRON_SECRET='secret';});
afterAll(()=>{if(original===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=original;});
test('rejects unauthenticated triggers before claiming jobs',async()=>{expect((await GET(request('wrong'))).status).toBe(401);expect(supabase.rpc).not.toHaveBeenCalled();});
test('claims bounded waves and acknowledges individual successes, failures and busy imports',async()=>{
 let claimed=false;
 (supabase.rpc as jest.Mock).mockImplementation(async name=>{if(name==='thrivv_claim_sync'){if(claimed)return{data:[],error:null};claimed=true;return{data:[{id:'a'},{id:'b'},{id:'c'}],error:null};}return{error:null};});
 (syncMemberWorkouts as jest.Mock).mockResolvedValueOnce({}).mockRejectedValueOnce(new Error('private upstream details')).mockRejectedValueOnce(new SyncBusyError());
 const r=await GET(request());expect(await r.json()).toEqual({queued:3,synced:1,deferred:2});
 expect(supabase.rpc).toHaveBeenCalledWith('thrivv_claim_sync',{p_lease:expect.any(String),p_limit:3});
 for(const [id,outcome] of [['a','ok'],['b','upstream_or_import_failed'],['c','busy']])expect(supabase.rpc).toHaveBeenCalledWith('thrivv_finish_sync',{p_user:id,p_lease:expect.any(String),p_outcome:outcome});
});
test('claim errors are visible and retryable',async()=>{(supabase.rpc as jest.Mock).mockResolvedValue({error:{message:'database unavailable'}});expect((await POST(request())).status).toBe(503);});
