'use client';
import {useEffect,useState} from 'react';
type Report={from:string;to:string;timezone:string;members:number;joined:number;firstVerified:number;repeatVisitors:number;firstReward:number;verifiedVisitDays:number;verifiedParticipants:number;visitsPerMemberWeek:number|null;week4Eligible:number;week4Participating:number;codesIssued:number;confirmedUse:number;rejected:number;expired:number;refunded:number;unknownMembershipDates:number;weekly:{week:string;visit_days:number;participants:number}[]};
export default function GymPilotAnalytics({gymId}:{gymId:string}) {
  const [from,setFrom]=useState('');const [query,setQuery]=useState('');const [revision,setRevision]=useState(0);const [data,setData]=useState<Report|null>(null);const [error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();setData(null);setError('');
    fetch(`/api/gym/${gymId}/pilot?from=${query}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});
    return ()=>controller.abort();},[gymId,query,revision]);
  return <section className="dark-card space-y-5 p-6"><h2 className="text-xl font-semibold">Pilot participation and rewards</h2>
    <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();setQuery(from);setRevision(v=>v+1);}}><label className="text-sm">Report start<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-2 block rounded-lg border border-white/15 bg-black/20 p-3" /></label><button className="btn-primary px-4 py-3 text-sm">Update report</button>{data && <a href={`/api/gym/${gymId}/pilot?from=${data.from}&format=csv`} className="px-4 py-3 text-sm text-thrivv-gold-400 underline">Download CSV</a>}</form>
    {error && <p role="alert">{error}</p>}{!data && !error && <p role="status">Loading verified participation…</p>}
    {data && <><p className="text-xs text-thrivv-text-muted">{data.from} – {data.to} · {data.timezone}</p>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Joined in period',data.joined],['First verified visit',data.firstVerified],['Two or more visit days',data.repeatVisitors],['First reward issued',data.firstReward]].map(([label,value])=><div key={label} className="rounded-xl border border-white/10 p-4"><p className="text-xs text-thrivv-text-secondary">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</div>
      <p className="text-xs text-thrivv-text-muted">These four counts follow current members who joined during this period.</p>
      <div className="grid gap-4 sm:grid-cols-2"><div><h3 className="font-medium">Verified attendance</h3><p className="mt-2 text-sm">{data.verifiedVisitDays} unique member visit days · {data.verifiedParticipants} participants</p><p className="mt-2 text-sm">{data.visitsPerMemberWeek ?? '—'} visit days per member per week</p><p className="mt-2 text-sm">Week 4: {data.week4Eligible ? `${data.week4Participating} of ${data.week4Eligible} eligible members (${Math.round(100*data.week4Participating/data.week4Eligible)}%)` : 'No completed four-week cohorts yet'}</p></div>
      <div><h3 className="font-medium">Reward outcomes</h3><p className="mt-2 text-sm">{data.codesIssued} issued · {data.confirmedUse} merchant-confirmed uses</p><p className="mt-2 text-sm">{data.rejected} rejected · {data.expired} expired · {data.refunded} refunded</p></div></div>
      {!!data.weekly.length && <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Weekly verified participation</caption><thead><tr><th className="py-2">Week starting</th><th>Visit days</th><th>Participants</th></tr></thead><tbody>{data.weekly.map(w=><tr key={w.week} className="border-t border-white/10"><td className="py-2">{w.week}</td><td>{w.visit_days}</td><td>{w.participants}</td></tr>)}</tbody></table></div>}
      <p className="text-xs leading-relaxed text-thrivv-text-muted">Each member counts once per gym day, including when both scanning methods were used. Week 4 means a verified visit on days 22–28 after joining and is shown only after that window closes. This measures participation, not paid membership retention. Reward attribution starts when the new issue tracking is deployed; older unattributed receipts are excluded. {data.unknownMembershipDates>0 && `${data.unknownMembershipDates} members have no joining date and are excluded from cohort rates.`}</p>
    </>}
  </section>;
}
