'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useClientSession} from '@/lib/client-session';
import {sendNativeReminders,type ScheduledReminder} from '@/lib/native-reminders';
type Preferences={available_rewards:boolean;voucher_expiry:boolean;weekly_target:number};
type Data={preferences:Preferences;reminders:{id:string;title:string;body:string;href:string}[];scheduled:ScheduledReminder[]};
export default function ReminderPage(){const {user}=useClientSession();return user?<Reminders key={user.id} userId={user.id}/>:<p>Loading reminders…</p>;}
function Reminders({userId}:{userId:string}){
 const [data,setData]=useState<Data|null>(null);const [prefs,setPrefs]=useState<Preferences>({available_rewards:false,voucher_expiry:false,weekly_target:0});const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();fetch(`/api/member/notifications?memberId=${userId}`,{cache:'no-store',signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('Unable to load reminders.');return r.json();}).then(d=>{setData(d);setPrefs(d.preferences);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[userId,revision]);
 useEffect(()=>{const listener=(e:Event)=>{const detail=(e as CustomEvent).detail;setMessage(detail?.granted?'Device reminders updated.':'Device notifications are off. Enable them in your device settings to receive reminders.');};window.addEventListener('thrivv:native-reminders',listener);return()=>window.removeEventListener('thrivv:native-reminders',listener);},[]);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/member/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...prefs,expectedUserId:userId,requestId:crypto.randomUUID()}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('Preferences were not saved. Please retry.');setMessage('Reminder preferences saved.');setRevision(v=>v+1);window.dispatchEvent(new Event('thrivv:reminders-changed'));}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <div className="mx-auto max-w-2xl space-y-6"><h1 className="text-3xl font-semibold">Useful reminders</h1><p className="text-sm text-thrivv-text-secondary">Choose what helps. All reminders start off. You can change them any time.</p>{error && <p role="alert">{error} <button className="underline" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}
 <form className="premium-card space-y-5 p-6" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!data || busy} className="space-y-5"><label className="flex gap-3"><input type="checkbox" checked={prefs.available_rewards} onChange={e=>setPrefs({...prefs,available_rewards:e.target.checked})}/>Show rewards I can redeem</label><label className="flex gap-3"><input type="checkbox" checked={prefs.voucher_expiry} onChange={e=>setPrefs({...prefs,voucher_expiry:e.target.checked})}/>Remind me before a saved voucher expires</label><label className="block">My weekly attendance target<select value={prefs.weekly_target} onChange={e=>setPrefs({...prefs,weekly_target:Number(e.target.value)})} className="mt-2 block w-full rounded-lg border border-white/15 bg-black/20 p-3">{[0,1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n?`${n} visit days`:'Off'}</option>)}</select></label><button className="btn-primary px-5 py-3">{busy?'Saving…':'Save preferences'}</button></fieldset></form>
 {message && <p role="status" className="text-sm text-thrivv-gold-400">{message}</p>}
 <section className="space-y-3"><h2 className="font-semibold">For you</h2>{data?.reminders.map(r=><Link key={r.id} href={r.href} className="block rounded-xl border border-white/10 p-4"><h3>{r.title}</h3><p className="mt-1 text-sm text-thrivv-text-secondary">{r.body}</p></Link>)}{data && !data.reminders.length && <p className="text-sm text-thrivv-text-muted">Nothing needs your attention right now.</p>}</section>
 <div className="rounded-xl border border-white/10 p-5"><button disabled={!data || busy} className="text-sm text-thrivv-gold-400 underline" onClick={()=>{if(!sendNativeReminders(data?.scheduled||[],true))setMessage('Device reminders are available in the updated Thrivv app. Your reminders are available here in the meantime.');}}>Enable reminders on this device</button><p className="mt-3 text-xs text-thrivv-text-muted">The updated app schedules one voucher reminder 24 hours before expiry and, if needed, one Saturday check-in for your weekly target. It refreshes the next seven days when opened. Available rewards appear here. Device delivery depends on your notification settings.</p></div>
 </div>;
}
